### ISSUE TITLE
Matrix build

### ISSUE THREAD

**Issue by PlatinumCD** [E4S-Project/e4s-alc#34]
Image I wanted to build `trilinos` containers for multiple operating systems, with different compilers and different compiler versions. This feature would build out all the `Dockerfile`s needed.

Given something similar to the following in the `.yaml` file:
```
base-image-matrix:
  - rhel8
  - ubuntu
  - centos

spack-compiler-matrix:
  - gcc:
     - 10.2
     - 11.3
     - 12.0

  - clang
     - 9.0.0
     - 12.0.0
     - 16.0.6

  - intel-oneapi-compiler:
     - latest

spack-packages:
  - trilinos
```
This would produce the directory `dockerfiles`:
```
+ dockerfiles:
|-- Dockerfile.rhel8-gcc-10.2-trilinos
|-- Dockerfile.rhel8-gcc-11.3-trilinos
|-- Dockerfile.rhel8-gcc-12.0-trilinos
|-- Dockerfile.rhel8-clang-9.0.0-trilinos
|-- Dockerfile.rhel8-clang-12.0.0-trilinos
|-- Dockerfile.rhel8-clang-16.0.6-trilinos
|-- Dockerfile.rhel8-intel-oneapi-compiler-latest-trilinos
|-- Dockerfile.ubuntu-gcc-10.2-trilinos
|-- Dockerfile.ubuntu-gcc-11.3-trilinos
|-- Dockerfile.ubuntu-gcc-12.0-trilinos
|-- Dockerfile.ubuntu-clang-9.0.0-trilinos
|-- Dockerfile.ubuntu-clang-12.0.0-trilinos
|-- Dockerfile.ubuntu-clang-16.0.6-trilinos
|-- Dockerfile.ubuntu-intel-oneapi-compiler-latest-trilinos
|-- Dockerfile.centos-gcc-10.2-trilinos
|-- Dockerfile.centos-gcc-11.3-trilinos
|-- Dockerfile.centos-gcc-12.0-trilinos
|-- Dockerfile.centos-clang-9.0.0-trilinos
|-- Dockerfile.centos-clang-12.0.0-trilinos
|-- Dockerfile.centos-clang-16.0.6-trilinos
|-- Dockerfile.centos-intel-oneapi-compiler-latest-trilinos
```
